const CONFIG = {
  barName: "Golazo Tavern & Tap",
  tagline: "Houston's home for World Cup 2026 watch parties",
  address: "1420 Main St, Houston, TX 77002",
  hours: "Mon–Sun · 11 AM – 2 AM",
  phone: "(713) 555-0198",
  instagram: "@golazotavern",
  facebook: "GolazoTavernHouston",
  brandColor: "#0B3D2E",
  brandLight: "#1A6B4F",
  brandText: "#F5F0E8",
  formEndpoint: "https://formspree.io/f/xpwzgkny",
  specials: [
    {
      icon: "ti-beer",
      name: "Pitcher of the Match",
      desc: "$18 domestic pitchers during every live World Cup kickoff",
    },
    {
      icon: "ti-tools-kitchen-2",
      name: "Taco Trio",
      desc: "Three street tacos with chips & salsa — $12 all tournament long",
    },
    {
      icon: "ti-glass-cocktail",
      name: "Margarita Madness",
      desc: "$8 house margaritas whenever Mexico or USA is on the big screen",
    },
    {
      icon: "ti-burger",
      name: "Halftime Burger",
      desc: "Double patty + fries for $14, available 30 min before and after halftime",
    },
  ],
  matches: [
    {
      teams: "Mexico vs South Africa",
      stage: "Group A",
      venue: "Estadio Azteca, Mexico City",
      date: "2026-06-11",
      time: "Jun 11 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "South Korea vs Czechia",
      stage: "Group A",
      venue: "Estadio Akron, Guadalajara",
      date: "2026-06-11",
      time: "Jun 11 · 9:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Australia vs Türkiye",
      stage: "Group D",
      venue: "BC Place, Vancouver",
      date: "2026-06-12",
      time: "Jun 12 · 11:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Canada vs Bosnia and Herzegovina",
      stage: "Group B",
      venue: "BMO Field, Toronto",
      date: "2026-06-12",
      time: "Jun 12 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "USA vs Paraguay",
      stage: "Group D",
      venue: "SoFi Stadium, Los Angeles",
      date: "2026-06-12",
      time: "Jun 12 · 8:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Qatar vs Switzerland",
      stage: "Group B",
      venue: "Levi's Stadium, San Francisco Bay Area",
      date: "2026-06-13",
      time: "Jun 13 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Brazil vs Morocco",
      stage: "Group C",
      venue: "MetLife Stadium, New York/New Jersey",
      date: "2026-06-13",
      time: "Jun 13 · 5:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Haiti vs Scotland",
      stage: "Group C",
      venue: "Gillette Stadium, Boston",
      date: "2026-06-13",
      time: "Jun 13 · 8:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Germany vs Curaçao",
      stage: "Group E",
      venue: "NRG Stadium, Houston",
      date: "2026-06-14",
      time: "Jun 14 · 12:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Netherlands vs Japan",
      stage: "Group F",
      venue: "AT&T Stadium, Dallas",
      date: "2026-06-14",
      time: "Jun 14 · 3:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Ivory Coast vs Ecuador",
      stage: "Group E",
      venue: "Lincoln Financial Field, Philadelphia",
      date: "2026-06-14",
      time: "Jun 14 · 6:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Sweden vs Tunisia",
      stage: "Group F",
      venue: "Estadio BBVA, Monterrey",
      date: "2026-06-14",
      time: "Jun 14 · 9:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Spain vs Cape Verde",
      stage: "Group H",
      venue: "Mercedes-Benz Stadium, Atlanta",
      date: "2026-06-15",
      time: "Jun 15 · 11:00 AM CT",
      status: "upcoming",
    },
    {
      teams: "Austria vs Jordan",
      stage: "Group J",
      venue: "Levi's Stadium, San Francisco Bay Area",
      date: "2026-06-15",
      time: "Jun 15 · 11:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Belgium vs Egypt",
      stage: "Group G",
      venue: "Lumen Field, Seattle",
      date: "2026-06-15",
      time: "Jun 15 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Saudi Arabia vs Uruguay",
      stage: "Group H",
      venue: "Hard Rock Stadium, Miami",
      date: "2026-06-15",
      time: "Jun 15 · 5:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Iran vs New Zealand",
      stage: "Group G",
      venue: "SoFi Stadium, Los Angeles",
      date: "2026-06-15",
      time: "Jun 15 · 8:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "France vs Senegal",
      stage: "Group I",
      venue: "MetLife Stadium, New York/New Jersey",
      date: "2026-06-16",
      time: "Jun 16 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Iraq vs Norway",
      stage: "Group I",
      venue: "Gillette Stadium, Boston",
      date: "2026-06-16",
      time: "Jun 16 · 5:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Argentina vs Algeria",
      stage: "Group J",
      venue: "Arrowhead Stadium, Kansas City",
      date: "2026-06-16",
      time: "Jun 16 · 8:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Portugal vs Congo DR",
      stage: "Group K",
      venue: "NRG Stadium, Houston",
      date: "2026-06-17",
      time: "Jun 17 · 12:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "England vs Croatia",
      stage: "Group L",
      venue: "AT&T Stadium, Dallas",
      date: "2026-06-17",
      time: "Jun 17 · 3:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Ghana vs Panama",
      stage: "Group L",
      venue: "BMO Field, Toronto",
      date: "2026-06-17",
      time: "Jun 17 · 6:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Uzbekistan vs Colombia",
      stage: "Group K",
      venue: "Estadio Azteca, Mexico City",
      date: "2026-06-17",
      time: "Jun 17 · 9:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Czechia vs South Africa",
      stage: "Group A",
      venue: "Mercedes-Benz Stadium, Atlanta",
      date: "2026-06-18",
      time: "Jun 18 · 11:00 AM CT",
      status: "upcoming",
    },
    {
      teams: "Switzerland vs Bosnia and Herzegovina",
      stage: "Group B",
      venue: "SoFi Stadium, Los Angeles",
      date: "2026-06-18",
      time: "Jun 18 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Canada vs Qatar",
      stage: "Group B",
      venue: "BC Place, Vancouver",
      date: "2026-06-18",
      time: "Jun 18 · 5:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Mexico vs South Korea",
      stage: "Group A",
      venue: "Estadio Akron, Guadalajara",
      date: "2026-06-18",
      time: "Jun 18 · 8:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Türkiye vs Paraguay",
      stage: "Group D",
      venue: "Levi's Stadium, San Francisco Bay Area",
      date: "2026-06-19",
      time: "Jun 19 · 10:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Tunisia vs Japan",
      stage: "Group F",
      venue: "Estadio BBVA, Monterrey",
      date: "2026-06-19",
      time: "Jun 19 · 11:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "USA vs Australia",
      stage: "Group D",
      venue: "Lumen Field, Seattle",
      date: "2026-06-19",
      time: "Jun 19 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Scotland vs Morocco",
      stage: "Group C",
      venue: "Gillette Stadium, Boston",
      date: "2026-06-19",
      time: "Jun 19 · 5:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Brazil vs Haiti",
      stage: "Group C",
      venue: "Lincoln Financial Field, Philadelphia",
      date: "2026-06-19",
      time: "Jun 19 · 8:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Netherlands vs Sweden",
      stage: "Group F",
      venue: "NRG Stadium, Houston",
      date: "2026-06-20",
      time: "Jun 20 · 12:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Germany vs Ivory Coast",
      stage: "Group E",
      venue: "BMO Field, Toronto",
      date: "2026-06-20",
      time: "Jun 20 · 3:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Ecuador vs Curaçao",
      stage: "Group E",
      venue: "Arrowhead Stadium, Kansas City",
      date: "2026-06-20",
      time: "Jun 20 · 7:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Spain vs Saudi Arabia",
      stage: "Group H",
      venue: "Mercedes-Benz Stadium, Atlanta",
      date: "2026-06-21",
      time: "Jun 21 · 11:00 AM CT",
      status: "upcoming",
    },
    {
      teams: "Belgium vs Iran",
      stage: "Group G",
      venue: "SoFi Stadium, Los Angeles",
      date: "2026-06-21",
      time: "Jun 21 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Uruguay vs Cape Verde",
      stage: "Group H",
      venue: "Hard Rock Stadium, Miami",
      date: "2026-06-21",
      time: "Jun 21 · 5:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "New Zealand vs Egypt",
      stage: "Group G",
      venue: "BC Place, Vancouver",
      date: "2026-06-21",
      time: "Jun 21 · 8:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Jordan vs Algeria",
      stage: "Group J",
      venue: "Levi's Stadium, San Francisco Bay Area",
      date: "2026-06-22",
      time: "Jun 22 · 10:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Argentina vs Austria",
      stage: "Group J",
      venue: "AT&T Stadium, Dallas",
      date: "2026-06-22",
      time: "Jun 22 · 12:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "France vs Iraq",
      stage: "Group I",
      venue: "Lincoln Financial Field, Philadelphia",
      date: "2026-06-22",
      time: "Jun 22 · 4:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Norway vs Senegal",
      stage: "Group I",
      venue: "MetLife Stadium, New York/New Jersey",
      date: "2026-06-22",
      time: "Jun 22 · 7:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Portugal vs Uzbekistan",
      stage: "Group K",
      venue: "NRG Stadium, Houston",
      date: "2026-06-23",
      time: "Jun 23 · 12:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "England vs Ghana",
      stage: "Group L",
      venue: "Gillette Stadium, Boston",
      date: "2026-06-23",
      time: "Jun 23 · 3:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Panama vs Croatia",
      stage: "Group L",
      venue: "BMO Field, Toronto",
      date: "2026-06-23",
      time: "Jun 23 · 6:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Colombia vs Congo DR",
      stage: "Group K",
      venue: "Estadio Akron, Guadalajara",
      date: "2026-06-23",
      time: "Jun 23 · 9:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Switzerland vs Canada",
      stage: "Group B",
      venue: "BC Place, Vancouver",
      date: "2026-06-24",
      time: "Jun 24 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Bosnia and Herzegovina vs Qatar",
      stage: "Group B",
      venue: "Lumen Field, Seattle",
      date: "2026-06-24",
      time: "Jun 24 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Scotland vs Brazil",
      stage: "Group C",
      venue: "Hard Rock Stadium, Miami",
      date: "2026-06-24",
      time: "Jun 24 · 5:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Morocco vs Haiti",
      stage: "Group C",
      venue: "Mercedes-Benz Stadium, Atlanta",
      date: "2026-06-24",
      time: "Jun 24 · 5:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Czechia vs Mexico",
      stage: "Group A",
      venue: "Estadio Azteca, Mexico City",
      date: "2026-06-24",
      time: "Jun 24 · 8:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "South Africa vs South Korea",
      stage: "Group A",
      venue: "Estadio BBVA, Monterrey",
      date: "2026-06-24",
      time: "Jun 24 · 8:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Curaçao vs Ivory Coast",
      stage: "Group E",
      venue: "Lincoln Financial Field, Philadelphia",
      date: "2026-06-25",
      time: "Jun 25 · 3:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Ecuador vs Germany",
      stage: "Group E",
      venue: "MetLife Stadium, New York/New Jersey",
      date: "2026-06-25",
      time: "Jun 25 · 3:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Japan vs Sweden",
      stage: "Group F",
      venue: "AT&T Stadium, Dallas",
      date: "2026-06-25",
      time: "Jun 25 · 6:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Tunisia vs Netherlands",
      stage: "Group F",
      venue: "Arrowhead Stadium, Kansas City",
      date: "2026-06-25",
      time: "Jun 25 · 6:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Türkiye vs USA",
      stage: "Group D",
      venue: "SoFi Stadium, Los Angeles",
      date: "2026-06-25",
      time: "Jun 25 · 9:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Paraguay vs Australia",
      stage: "Group D",
      venue: "Levi's Stadium, San Francisco Bay Area",
      date: "2026-06-25",
      time: "Jun 25 · 9:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Egypt vs Iran",
      stage: "Group G",
      venue: "Lumen Field, Seattle",
      date: "2026-06-26",
      time: "Jun 26 · 10:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "New Zealand vs Belgium",
      stage: "Group G",
      venue: "BC Place, Vancouver",
      date: "2026-06-26",
      time: "Jun 26 · 10:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Norway vs France",
      stage: "Group I",
      venue: "Gillette Stadium, Boston",
      date: "2026-06-26",
      time: "Jun 26 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Senegal vs Iraq",
      stage: "Group I",
      venue: "BMO Field, Toronto",
      date: "2026-06-26",
      time: "Jun 26 · 2:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Cape Verde vs Saudi Arabia",
      stage: "Group H",
      venue: "NRG Stadium, Houston",
      date: "2026-06-26",
      time: "Jun 26 · 7:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Uruguay vs Spain",
      stage: "Group H",
      venue: "Estadio Akron, Guadalajara",
      date: "2026-06-26",
      time: "Jun 26 · 7:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Panama vs England",
      stage: "Group L",
      venue: "MetLife Stadium, New York/New Jersey",
      date: "2026-06-27",
      time: "Jun 27 · 4:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Croatia vs Ghana",
      stage: "Group L",
      venue: "Lincoln Financial Field, Philadelphia",
      date: "2026-06-27",
      time: "Jun 27 · 4:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Colombia vs Portugal",
      stage: "Group K",
      venue: "Hard Rock Stadium, Miami",
      date: "2026-06-27",
      time: "Jun 27 · 6:30 PM CT",
      status: "upcoming",
    },
    {
      teams: "Congo DR vs Uzbekistan",
      stage: "Group K",
      venue: "Mercedes-Benz Stadium, Atlanta",
      date: "2026-06-27",
      time: "Jun 27 · 6:30 PM CT",
      status: "upcoming",
    },
    {
      teams: "Algeria vs Austria",
      stage: "Group J",
      venue: "Arrowhead Stadium, Kansas City",
      date: "2026-06-27",
      time: "Jun 27 · 9:00 PM CT",
      status: "upcoming",
    },
    {
      teams: "Jordan vs Argentina",
      stage: "Group J",
      venue: "AT&T Stadium, Dallas",
      date: "2026-06-27",
      time: "Jun 27 · 9:00 PM CT",
      status: "upcoming",
    },
  ],
};
